### ISSUE TITLE
no max number of clicks?

### ISSUE THREAD

**Issue by srcreigh** [othyn/macos-auto-clicker#1]
Hi there, thanks for the beautiful app. Unfortunately it doesn't quite suit my purposes since 10k clicks (1 per second) is only about 2 hours of click time. I'd like to leave auto clicking running overnight / all day.

No pressure to actually add this feature, just thought you'd like to know that I tried it out!

By the way, I found your repo by searching "macos auto clicker site:github.com" in Google.

**Comment by othyn** [comment]
Thanks! Good to know for future and I'm glad its helping you out 😄

I've just released v1.2.0 in which has a much higher limit set (100,000,000) so even setting that going with the default 50ms interval would take nearly 2 months to complete. So hopefully that solves your problem!

I've also done some minor UI/UX changes and made the app overall less restrictive.

**Comment by srcreigh** [comment]
Cool thanks! I'll give version 1.2 a go sometime this week.

**Comment by danh-geo** [comment]
Nice work @othyn 👍

**Comment by srcreigh** [comment]
Thank you I've been using the app successfully now for the past week running it more/less constantly on my 2nd laptop.

**Comment by othyn** [comment]
Glad I could help 😄
