### ISSUE TITLE
As a user, I want to be able to specify the pressed key during the action phase

### ISSUE THREAD

**Issue by danh-geo** [othyn/macos-auto-clicker#2]
Firstly, great project! Really nice job with it and well written.

This is a feature request, but I think it might be nice/useful if the user could specify what input they want repeated. Obviously right now its set to left click (which makes sense as its an auto clicker 😄 ) But it would be nice if before the user taps the [Start] button, that they could configure the input.
e.g.
1. Users presses [Configure input] (default is currently left click)
2. The app then listens to what the user presses next, e.g. right click, or even a key on the keyboard.
3. Whatever the user pressed is now the thing that will get repeated. So if I right clicked, thats the thing now that will get repeated.

The other thing (and perhaps this is a separate feature request I apologise) would be to specify how many times it should perform the input action after the interval. e.g. Perhaps the user wants to double (left) click every 3 seconds, as opposed to have it click once every 3 seconds. It might be a nice feature to be able to specify how many times it should perform the input.

Again, great job and thanks for this awesome app 👍

**Comment by othyn** [comment]
Awesome idea! Would love to implement something like this.

May not be soon, but I'll have an explore.

And yeah, I've spun out the latter about the 'amount of actions' into Issue #3 and I'll take a look at that, as I think that will be the easier of the two to implement as a point release.

As part of this, I'd love to have a re-factor of the UI to make this easier to understand. (see now Issue #4)

Perhaps in the layout of:

"Every `<duration field>` press `<input field>` `<amount of actions field>` times and wait `<duration field>` before doing it again for a total of `<amount of iterations field>` times."

**Comment by othyn** [comment]
Depends on Issue #4 being implemented first to stop a UI rework post implementation.

**Comment by othyn** [comment]
This feature has been added in the latest `dev` branch 😄

**Comment by othyn** [comment]
There is an alpha build in the releases with this feature in 👍
