### ISSUE TITLE
As a user I would like to be able to click every 1.5 seconds (1500 ms)

### ISSUE THREAD

**Issue by danaspiegel** [othyn/macos-auto-clicker#33]
**Is your feature request related to a problem? Please describe.**
the largest value for milliseconds is 1000, but I would like to click every 1.5 seconds or 1500 milliseconds, which isn't possible since I can't enter a fractional second nor enter more than 1000 milliseconds.

**Describe the solution you'd like**
be able to enter more than 1000 milliseconds or enter fractional seconds

**Describe alternatives you've considered**
n/a

**Comment by othyn** [comment]
Should be a quick fix, I thought I'd removed the cap on the seconds value to stop artificial limits like this. Shall update and push out a new build!

**Comment by othyn** [comment]
[v1.3.2](https://github.com/othyn/macos-auto-clicker/releases/tag/v1.3.2) is now released with this cap removed, enjoy!
