### ISSUE TITLE
As a user, I would like support for localisation

### ISSUE THREAD

**Issue by othyn** [othyn/macos-auto-clicker#36]
As it says on the tin, this would just be the ground work required to start accepting language support PR's as part of #10

**Comment by raimeenakshi** [comment]
Hi @othyn to be clear, you just wish to add Localizable.strings file added to your project, or something else?

**Comment by othyn** [comment]
@Max-Rai thank you for opening a dialogue on implementing this! 😄

This is the first time for me localising a macOS project, is using Localisable.strings the best approach for this in your opinion? It's the native approach isn't it?

From my limited knowledge on this, I think this is the direction that would be good for this project (given it's the native approach)

I'm in limited contact until late July (25th~ish), just if I don't respond 😄

**Comment by raimeenakshi** [comment]
Hi @othyn attaching few resources which are common for all Apple platforms to support Localization. One can go down the rabbit hole on these documentations, depending on how curious they are 😅
- https://developer.apple.com/localization/
- https://developer.apple.com/documentation/xcode/localization
- https://www.hackingwithswift.com/example-code/uikit/how-to-localize-your-ios-app

**Comment by othyn** [comment]
@Max-Rai thanks for those, very interesting reads! From those I also came across:

- https://www.raywenderlich.com/27469286-swiftui-localization-tutorial-for-ios-getting-started
- https://github.com/mohakapt/Stringz

... now just to find the time to implement it!
