### ISSUE TITLE
macOS Ventura Support

### ISSUE THREAD

**Issue by othyn** [othyn/macos-auto-clicker#42]
As was announced during the WWDC22 keynote speech, the next release of macOS is Ventura and is to be expected later in 2022.

I haven't run Auto Clicker on macOS Ventura yet, as at the moment I don't have a spare machine to run the Ventura Beta on (and haven't had time to spin up a VM), so at this time I have no idea if the app works on Ventura as-is ~ although if you've been running it on Ventura, it would be great to have some feedback on this so please leave a comment on this thread below.

I'm happily accepting any PR's on support for Ventura if support patches are required.

The only other issue is that I will need to wait for GitHub to release a new runner for `macos-13` in order to have the CI/CD flow generate builds for Big Sur, Monterey _and_ the newly released Ventura. No doubt there will also be required upgrades and patching to get all that to work due to newer versions of packages (maybe) and Xcode also being required.

**Comment by Zw211** [comment]
Hello, I'm running macOS Ventura and everything is working as intended. You can safely say it is compatible with this version :)

**Comment by othyn** [comment]
@Zw211 ah thats excellent news, thank you for trying it and providing feedback! Shall keep tabs on it as the beta progresses ;)

**Comment by othyn** [comment]
So I've just upgraded to Ventura 13.0 at the main release, everything appears to work fine, there is just a visual bug regarding the vertical spacing of the text, as seen below.

<img width="662" alt="Screenshot 2022-10-26 at 10 04 50" src="https://user-images.githubusercontent.com/7256684/197984053-fe2d0d58-575c-4df1-a5cb-ee19b6cfb026.png">

Everything else appears to work in my testing;

- [x] Quit app on main window close option
- [x] Hide dock icon option
- [x] Global keyboard shortcut options
- [x] Always keep the main window on top option
- [x] Appearance options
- [x] All menu bar functionality
- [x] All app functionality
