### ISSUE TITLE
App can’t be opened 

### ISSUE THREAD

**Issue by zisra** [othyn/macos-auto-clicker#50]
I get this error when opening the app: Auto Clicker can’t be opened because Apple cannot check it for malicious software.

**Comment by othyn** [comment]
Hey! 👋 

So this is as I don't have a paid developer account with Apple, I cannot sign the software with them so they can tell macOS everything is fine.

If you follow the steps in the Download section of the README, its very easy to get the app manually approved: https://github.com/othyn/macos-auto-clicker#floppy_disk-download

> When first using the app, you will need to right click the app and click 'Open' from within Finder, then on the macOS popup window select 'Open' again to trust this version of the app going forward. This is as at the moment I don't have a paid Apple developer account in order to notarize the app.

That should solve your issue! 😄

**Comment by zisra** [comment]
Thank you for the clarification. It’s a shame Apple makes developers pay to make their app usable.

**Comment by othyn** [comment]
> Thank you for the clarification. It’s a shame Apple makes developers pay to make their app usable.

It is indeed! One day I'll get one and notarise the app, then all will be well.

Thanks for using the app, enjoy! 😄
