### ISSUE TITLE
As a user, I would like to see variable miliseconds and changeable key to start  

### ISSUE THREAD

**Issue by sadopc** [othyn/macos-auto-clicker#55]
I love your app, and if you add this things this app would be great I think

**Comment by othyn** [comment]
Hi! Very welcome to suggestions, thank you for putting forward yours!

I don't quite understand what you mean though, can you provide more detail?

From my understanding on what you are proposing, I think the app already has those features built in;

- Milliseconds can currently be selected and changed on the current UI of the app.
- The shortcut key to start can be changed from within the apps preferences.
