### ISSUE TITLE
As a user, i got a bug when press start by hotkeys twice ( option + cmd + S )

### ISSUE THREAD

**Issue by lammerfalcon** [othyn/macos-auto-clicker#56]
When press option + cmd + S twice program go to the infinity loop, i cant stop program by clicking on button STOP, or press option + cmd + X

Macbook air m1, OS x 13

**Comment by othyn** [comment]
Thanks for the bug report, I'll have a look and get back to you to see if I can re-produce it.

**Comment by othyn** [comment]
Yep, can confirm!

You can start the timer multiple times using the keyboard shortcut and get the app stuck.

**Steps to reproduce:**

1. Open the app.
2. Press the 'Start' keyboard shortcut repeatedly.
3. The timer will start in the background as many times as the button is pressed, regardless of if its in pre-or-post countdown state.

**Ideas on what the problem could be:**

At a guess there is a boolean switch that is not checked when using the keyboard shortcut vs. using the button that stops the timer being instigated multiple times.

**Comment by othyn** [comment]
@lammerfalcon v1.5.0 of the app fixes this, I did mean to do a v1.4.x patch release but the CI/CD flow broke so its part of v1.5.0.

Download can be found on the releases page.

**Comment by lammerfalcon** [comment]
Thank you! I really like your program!
