### ISSUE TITLE
Your absolutely incredible app isn't opening for me!

### ISSUE THREAD

**Issue by WaffleDG** [othyn/macos-auto-clicker#60]
I tried setting the start and stop options to the same keypress, and the app quit on me and was never able to reopen again, no matter the version. Is there a fix for this, and if so, what is it?

**Comment by othyn** [comment]
This is a new one for me! Not heard of this occuring yet, mainly as it _should_ be impossible. 

The shortcuts library I use for recording the keyboard shortcuts in the app's preferences doesn't allow you to make them the same shortcut, in my testing. So thats an impressive feat to accomplish such a bug!

As a fix, you could try and delete your preferences file, located here:

```sh
~/Library/Preferences/com.othyn.auto-clicker.plist
```

Although I'm not sure if that will work as I cannot reproduce the bug.

**Comment by WaffleDG** [comment]
Oh! Sorry, i meant that i tried setting the keypress to nothing, and it registered as nothing. Then, i started the autoclicking and the app crashed. Also, i did try deleting the preferences file, but couldn't find it. Any ideas on what went wrong?

**Comment by WaffleDG** [comment]
Fixed it by deleting the preferences file and restarting. Thank you so much for the help!! :D

**Comment by othyn** [comment]
Ah super, glad its sorted!
