### ISSUE TITLE
Computer Crash

### ISSUE THREAD

**Issue by ghost** [othyn/macos-auto-clicker#63]
### Description

If you set it to Left Click 100000000 times, good luck getting your computer to work. I had to hold the power button for 20 seconds (meaning it force shutdown the computer), and it still lagged for the first minute.

### Version

1.5.0

### Steps to Reproduce

![Screenshot 2023-06-19 at 5 38 20 PM](https://github.com/othyn/macos-auto-clicker/assets/129239408/b4b844b4-b4f8-486e-b3a7-2ac4c3a39992)

### Device

Mac Mini

### Operating System

macOS Ventura 13.4

**Comment by othyn** [comment]
With the best will in the world, I don't know what action you expect me to take on this.

The field limits are set purposefully high so the application doesn't become opinionated and artificially limit the user.

If values are entered that exceed sane limits, then of course it will crash, but that is on you as the user and operator of your machine to determine.

The only 'fix' for this would be to impose artificial limits, which I don't want to do.

You're asking it to perform 100,000,000 clicks, every millisecond, 100,000,000 times over.

**Comment by ghost** [comment]
i just realized how dumb i am

**Comment by othyn** [comment]
Hahaha no worries, it happens to all of us.
