### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by sineld** [othyn/macos-auto-clicker#64]
### Description

Wouldn't it be great if there was an optional feature to display a notification when the process begins and ends?

### Desired Behavior

Notifications

**Comment by othyn** [comment]
Great suggestion! I'll take a look at this when I'm next looking at the project.

In the meantime, PR's are always welcome 😉

**Comment by AnonymousAlt0** [comment]
I could have a look at this over the weekend.

**Comment by sineld** [comment]
I use enable and disable too much. I'd be a very handy feature for me. I hope your reliese it soon. Thanks.

**Comment by othyn** [comment]
> I could have a look at this over the weekend.

Happy to accept PR's on this! From playing around with the notification API on iOS in Swift, it seems fairly simple to setup a wrapper and trigger them on device. Hopefully that experience translates well to macOS.

**Comment by othyn** [comment]
This will be in the next release, I'll fire one out now

**Comment by sineld** [comment]
Thank you for the prompt update, everyone.

I have downloaded the latest version and granted the necessary permissions, but it is not working as expected. I even tried removing it completely, restarting macOS, and reinstalling it, but the issue persists.

![2023-07-01 16-16-54 Auto Clicker](https://github.com/othyn/macos-auto-clicker/assets/445349/bc6413df-c729-4e77-a959-be6ae35ccb13)

**Comment by AnonymousAlt0** [comment]
I think I just experienced the same problem you're having. I was able to fix it by removing Auto Clicker from Accessibility settings outlined below, then opening the app and it worked as expected.

<img width="827" alt="SCR-20230701-niyw" src="https://github.com/othyn/macos-auto-clicker/assets/138115480/7b3d8457-ac33-459f-ad7f-4da2d4e60f3b">

**Comment by sineld** [comment]
@AnonymousAlt0 I got it worked as you directed me, thanks.
Notifications pops up when started and when finished **but** _no notifications is poping up_ on _manual stop_.

**Comment by othyn** [comment]
@AnonymousAlt0 super, thank you for debugging that - it would have been my suggestion too. Not entirely sure why it was necessary as the app identifier hasn't changed... only fix could be to try and do a permissions reset on application load.

@sineld thats by intention at the moment, notifications are only fired at specified automated start/stop points.

@AnonymousAlt0 that does raise an important consideration though, if the user cancels the timer, are notifications cleared?
