### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by sineld** [othyn/macos-auto-clicker#67]
### Description

Even I have changed the shortcuts of the app to start and stop, main app icon on taskbar still show cmd + F

### Version

1.6.1

### Steps to Reproduce

Change shortcuts in settings
Visit main menu app 

### Device

MacBook Pro

### Operating System

macOS Ventura 13.4.1

**Comment by othyn** [comment]
At the moment, it appears that the app requires a restart to reflect the change into the menu bar context menu.

Will need to debug this! Its probably something in the state lifecycle or needing to refresh the state of the menu bar.

**Comment by sineld** [comment]
I've restarted app but I still see the old shortcuts.

**Comment by othyn** [comment]
Huh, thats what fixed it for me. I've just tried it again and that is the reproducable scenario for me.

What shortcut are you trying to swap it from and to?

**Comment by sineld** [comment]
Start: CMD + F6
Stop: CMD + F8

Retried but still the same.
Actually it's not a big deal but I needed to mention when I came across.

**Comment by othyn** [comment]
Fixed in the latest release
