### ISSUE TITLE
Project URL in About Page

### ISSUE THREAD

**Issue by sineld** [othyn/macos-auto-clicker#73]
### Description

It would be beneficial to include this repository's URL on the about page. I had to spend an excessive amount of time searching for this page after having installed the software for a considerable period.

Furthermore, it would be advantageous to include the URL to this repository in the footer section of the main screen.

### Desired Behavior

Add repository URL to about page

**Comment by othyn** [comment]
Yep good idea, easily added!

Although I think the project URL to submit and issue is under the help menu already if you want it too.
