### ISSUE TITLE
macOS Sequoia support thread

### ISSUE THREAD

**Issue by othyn** [othyn/macos-auto-clicker#81]
### Description

This thread exists to gather feedback on macOS Sequoia support, if there are any issues and if there are a path to getting macOS Sequoia supported.

I don't have a Sequoia machine that I can test on, so I'd be open to any PR's fixing issues, but it will probably have to wait until beyond full release for me to debug and fix anything that comes up.

### Desired Behavior

Support for macOS Sequoia.

**Comment by 0x427279** [comment]
See #82

**Comment by othyn** [comment]
There is now a working build out for Sequoia, see the [releases](https://github.com/othyn/macos-auto-clicker/releases) page!
