### ISSUE TITLE
Main Menu Not Showing

### ISSUE THREAD

**Issue by MDanyalT** [othyn/macos-auto-clicker#82]
### Description

This might be due to my ignorance as I am unfamiliar with using github, but I have downloaded the file (only the file nothing else), opened it with all permissions granted however I do not see the menu (the colorful one). Furthemore the autoclicker itself is not working.

### Version

1.7.21 (5a1b91e)

### Steps to Reproduce

Download App File
Open

### Screenshots

<img width="857" alt="Screenshot 2024-08-17 at 8 04 44 PM" src="https://github.com/user-attachments/assets/8ea6deec-206c-4afe-b394-a7348df35cd5">
What I see when opening the app

### Device

macbook air m2 

### Operating System

MacOS 15.0

**Comment by 0x427279** [comment]
Exact same problem, also on MacOS Sequoia 15.0 (beta 5)

**Comment by othyn** [comment]
I don't have a Sequoia machine that I can test on, so I'd be open to PR's fixing this issue, but it will probably have to wait until beyond full release for me to debug and fix.

**Comment by tresf** [comment]
Sequoia was released as stable on September 16th, so this is likely to be reported more.  (I upgraded today and can now reproduce the OPs issue).

**Comment by othyn** [comment]
Sorry its taken me so long to get round to this, I'm pushing out a fix this morning as I have a working fix, if I can get a Sequoia build outputted.

One of those changes where it seems completely silly.

**Comment by othyn** [comment]
There is now a working build out for Sequoia, see the [releases](https://github.com/othyn/macos-auto-clicker/releases) page!

**Comment by tresf** [comment]
> There is now a working build out for Sequoia, see the [releases](https://github.com/othyn/macos-auto-clicker/releases) page!

Thanks!  What's not immediately obvious is how to fix this:

<img width="744" alt="image" src="https://github.com/user-attachments/assets/60c7f384-3abf-4934-b64b-b17e1b8339b5">

The permissions are still there from before.  I've tried to toggle them off and back on again but the yellow screen won't go away.  Is there -- by chance -- something in Gatekeeper preventing it from using Accessibility features?  Or is there a step other than the `sudo xattr -r -d com.apple.quarantine` that's needed now?

**Comment by tresf** [comment]
> > There is now a working build out for Sequoia, see the [releases](https://github.com/othyn/macos-auto-clicker/releases) page!
> 
> Thanks! What's not immediately obvious is how to fix this:

Ok, I removed `AutoClicker` from the listing by click `-` and then added it again manually and it's working.  Thanks!

**Comment by tresf** [comment]
Just realised the readme mentions this as well:

> There can sometimes be an issue with this, I'm not entirely sure why this occurs, as the bundle identifier for the app remains the same and therefor the granted permissions shouldn't either. MacOS gets 'stuck' thinking the app has permissions when it doesn't and so the permission splash screen for the app will never go away. To fix it, click the minus button at the bottom of the list of apps under macOS's Accessibility settings where Auto Clicker is listed to manually remove Auto Clicker from the list of permitted apps. Close Auto Clicker and re-open it and grant it access once again, which should fix the issue. https://github.com/othyn/macos-auto-clicker/issues/64#issuecomment-1615933048.
